version: "3.8"

services:
  postgres:
    container_name: bayzdelivery_db
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: bayzdelivery
      PGDATA: /data/postgres/bayztracker
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: oghazala@bayzat.com
      PGADMIN_DEFAULT_PASSWORD: toolS585
    ports:
      - "8080:80"
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
